server:
  port: ${PUERTO:8083}

spring:
  application:
    name: servicio-segmentacion

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/crm_maxiconecta}
    username: ${DB_USUARIO:crm}
    password: ${DB_PASSWORD:crm}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none

  flyway:
    schemas: segmentacion
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: health
